replicas: 3

## RabbitMQ Cluster image
##
image:
  name: neunnsy/rabbitmq-cluster
  pullPolicy: IfNotPresent

serviceAccount: true
serviceAccountName: rabbitmq

## Node port
##
rabbitmqNodePort: 5672

## RabbitMQ Manager port
##
rabbitmqManagerPort: 15672

## longName: true
## autoClusterType: k8s

serviceType: NodePort
httpNodePort: 31672
amqpNodePort: 30672
exporterNodePort: 32672

exporter:
  image: kbudde/rabbitmq-exporter
  pullPolicy: IfNotPresent
  port: 9090

storage:
  enabled: false
  accessMode: ReadWriteOnce
  isStorageClass: false
  storageClass:
  pvSelector:
  storageSpace: 2Gi